extends TestCase
## Cross-language contract with the TypeScript server: shared/tests/golden.json
## is generated by server/tools/genGolden.ts and checked on both sides.

var golden: Dictionary


func _init() -> void:
	golden = JSON.parse_string(FileAccess.get_file_as_string("res://shared/tests/golden.json"))


func test_codec_vectors() -> void:
	var codec := NetCodec.new(defs().protocol)
	for c in golden.codec:
		eq(codec.encode(c.dir, c.name, c.msg).hex_encode(), c.hex, "encode " + c.name)
		var back := codec.decode(c.dir, PackedByteArray(Array(c.hex.hex_decode())))
		eq(back.get("name", back.get("error")), c.name, "decode " + c.name)
		check(_same(back.get("msg"), c.msg), "decoded values of %s: %s vs %s" % [c.name, back.get("msg"), c.msg])
	var short := codec.decode("C2S", PackedByteArray([3, 1]))
	check(short.has("error"), "short frame rejected")
	var trailing := codec.encode("C2S", "ping", {"clientTime": 5})
	trailing.append(0)
	check(codec.decode("C2S", trailing).has("error"), "trailing bytes rejected")


func test_wave_formulas() -> void:
	var c: Dictionary = defs().waves
	for row in golden.waves:
		var wave := int(row.wave)
		near(WaveDirector.spawn_interval_for(c, wave), row.interval, 1e-4, "interval wave %d" % wave)
		for i in row.count.size():
			eq(WaveDirector.count_for(c, wave, i + 1), int(row.count[i]), "count wave %d players %d" % [wave, i + 1])
		for id in defs().zombies:
			near(WaveDirector.health_for(defs().zombies[id], wave), row[id].health, 1e-3, "%s health wave %d" % [id, wave])
			near(WaveDirector.speed_for(defs().zombies[id], wave), row[id].speed, 1e-4, "%s speed wave %d" % [id, wave])


func test_hits_moves_rays() -> void:
	for h in golden.hits:
		var r := HitTest.ray_character(_v3(h.o), _v3(h.d), Vector2(h.pos.x, h.pos.y), h.radius, h.headY, h.headR)
		near(r.get("t", -1.0), h.t, 1e-3, "hit distance")
		eq(r.get("head", false), h.head, "head flag")
	var map := MapData.from_dict(defs().maps[golden.map], float(defs().constants.player.stepHeight))
	for m in golden.moves:
		var p := map.move_circle(Vector2(m.pos.x, m.pos.y), Vector2(m.delta.x, m.delta.y), m.radius)
		near(p.x, m.result.x, 2e-3, "move x")
		near(p.y, m.result.y, 2e-3, "move y")
	for c in golden.rays:
		near(map.raycast(_v3(c.o), _v3(c.d), c.max), c.t, 2e-3, "raycast")


static func _v3(d: Dictionary) -> Vector3:
	return Vector3(d.x, d.y, d.z)


## Deep compare with a small float tolerance (JSON numbers are floats in Godot).
static func _same(a: Variant, b: Variant) -> bool:
	if a is Dictionary and b is Dictionary:
		if a.size() != b.size():
			return false
		for k in a:
			if not b.has(k) or not _same(a[k], b[k]):
				return false
		return true
	if a is PackedByteArray:
		a = Array(a)
	if a is Array and b is Array:
		if a.size() != b.size():
			return false
		for i in a.size():
			if not _same(a[i], b[i]):
				return false
		return true
	if (a is float or a is int) and (b is float or b is int):
		return absf(float(a) - float(b)) <= 1e-6 * maxf(1.0, absf(float(b)))
	return a == b
